services:
  traefik:
    image: traefik:v2.11
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--log.level=DEBUG"
    labels:
      - "traefik.http.routers.api.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8080:8080"

  tease:
    image: ghcr.io/prompt-edu/tease-client:latest
    container_name: tease
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tease.rule=PathPrefix(`/tease`)"
      - "traefik.http.routers.tease.service=tease"
      - "traefik.http.middlewares.tease-stripprefix.stripprefix.prefixes=/tease"
      - "traefik.http.routers.tease.middlewares=tease-stripprefix"
      - "traefik.http.services.tease.loadbalancer.server.port=80"
    build: ./client-react
    expose:
      - "80"

  tease-server:
    image: ghcr.io/prompt-edu/tease-server:latest
    container_name: tease-server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tease-server.rule=PathPrefix(`/tease.v1.TeamAllocationService`)"
      - "traefik.http.services.tease-server.loadbalancer.server.port=8081"
    build: ./server-go
    expose:
      - "8081"
